version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://Admin:Bookstore1234@cluster0.ljmf1p3.mongodb.net/
    volumes:
      - ./backend:/app
      - /app/node_modules  # Prevents overwriting container node_modules with host
    working_dir: /app
    command: ["npx", "nodemon", "app.js"]

